### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by vicgonva** [pablokbs/plex-rpi#24]
Buenos días,

Actualmente este proyecto está funcionando? 

He realizado el git clone, modificado el docker-compose.yaml con las configuraciones de red / unidad montada pero los dockers de transmission y flexget no acaban de levantar y no sé el motivo. 

![image](https://user-images.githubusercontent.com/65218571/103102766-cfd87f00-461d-11eb-9963-7b6c67e296fd.png)

Muchas gracias!

**Comment by jotaseme** [comment]
#23 Está resuelto aquí. Hay que agregar la carpeta complete en el storage.

**Comment by bepece1** [comment]
> #23 Está resuelto aquí. Hay que agregar la carpeta complete en el storage.
> 
> EDITO: el issue que enlazo únicamente soluciona el error del contenedor de flex, el de transmission no he sido capaz de hacerlo funcionar tampoco, mismo error. Alguna idea?

Tengo el mismo problemas con el contenedor transmission, la cosa es que no genera ningun error y tpco genera logs en docker por lo que no sé como solucionarlo.

Alguna idea??? @pablokbs @jotaseme

**Comment by AlexRiosJ** [comment]
Estoy teniendo el mismo problema con el contenedor de transmission, no he encontrado ninguna manera de echarlo a andar.

**Comment by bepece1** [comment]
> Estoy teniendo el mismo problema con el contenedor de transmission, no he encontrado ninguna manera de echarlo a andar.

Pues siento decirte que nadie me ha contestado sobre este asunto 😞

**Comment by Keviinplz** [comment]
Logre correr los contenedores, pero aun no logro que FlexGet descargue los torrents, mañana puedo subir mis configuraciones y setup!

**Comment by bepece1** [comment]
> Logre correr los contenedores, pero aun no logro que FlexGet descargue los torrents, mañana puedo subir mis configuraciones y setup!
> 
> transmission funciona bien (descarga los torrents que le paso)
> flexget funciona aparentemente bien (hizo el trabajo de mover el video a la libreria de plex)
> plex funciona bien
> 
> solo me falta conseguir que flexget busque y descargue las peliculas y series automaticamente

Yeahhh, impaciente de ver cómo lo hiciste

**Comment by Keviinplz** [comment]
Hola!

Estoy trabajando sobre una Raspberry PI 4 de 2GB con Ubuntu 20.04

En el Docker Compose, para PLEX utilice la Imagen de [LinuxServer](https://hub.docker.com/r/linuxserver/plex), me pareció mas intuitiva y fácil.

Para Transmission le agregue una configuración nueva, ya que me dio problemas con el uso de Internet, sin embargo, aplique esta configuración a la Raspberry, así que no estoy seguro si esa configuración tiene que correr a nivel de host (es decir, la raspberry) o a nivel del contenedor.

Para FlexGet mantuve los cambios, usando la versión ARM que se encuentra en este mismo repositorio.

PD: Utilice la SD de la raspberry porque soy pobre y no tengo HDD :(

docker.compose.yaml
```yaml
version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex # imagen de linuxserver
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - PLEX_CLAIM= # aqui use un claim, pero es opcional
    volumes:
      - /home/kevin/plex/config:/config
      - /home/kevin/plex/media/movies:/movies
      - /home/kevin/plex/media/series:/tv

  transmission:
    image: jaymoulin/transmission
    command: transmission-daemon -f -g /config
    container_name: transmission
    volumes:
      - /home/kevin/plex/transmission:/config
      - ${STORAGE}:/downloads
      - /home/kevin/plex/transmission/config/sysctl.conf:/etc/sysctl.conf # nuevo 
    ports:
      - "9091:9091"
      - "51413:51413"
    restart: unless-stopped

  flexget:
    build: flexget
    container_name: flexget
    volumes:
      - /home/kevin/plex/flexget:/config
      - ${STORAGE}:/downloads
      - ${MEDIA}:/storage
    ports:
      - "5050:5050"
    environment:
      - TORRENT_PLUGIN=transmission
      - FB_WEBUI_PASSWD=${TRANSMISSION_PASSWORD}
    restart: unless-stopped
    links:
      - transmission
```
 
/home/kevin/plex/transmission/config/sysctl.conf
```env
net.core.rmem_max = 4194304
net.core.wmem_max = 1048576
```

FlexGet Dockerfile:

```Dockerfile
FROM armhf/alpine
MAINTAINER bren

RUN apk add --update \
  tzdata \
  python \
  py-pip \
  ca-certificates \
  && pip install --no-cache-dir --disable-pip-version-check flexget==2.21.0 transmissionrpc==0.11 \
  && rm -rf /var/cache/apk/*

RUN apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/main tinyxml2 && \
    apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community mediainfo && \
    apk add --update ffmpeg && \
    rm -rf /var/cache/apk/*

# Copy local files
COPY files/ /

# add default volumes
VOLUME /config /data
WORKDIR /config

# expose port for flexget webui
EXPOSE 3539 3539/tcp

# run init.sh to set uid, gid, permissions and to launch flexget
RUN chmod +x /scripts/init.sh
CMD ["/scripts/init.sh"]
```

Para la configuracion de FlexGet, use las mismas que @pablokbs 

```yaml
web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1

templates:
  tv:
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      tv:
      - Black Mirror
      - Mr Robot
      - Rick and Morty
      - Silicon Valley
      - The Walking Dead
      - WandaVision

    transmission:
      host: transmission
      port: 9091
      username: keviinplz
      password: # owo

tasks:
  eztvrss:
    rss: https://eztv.re/ezrss.xml
    template: tv
    priority: 2
  showrss:
    rss: # owo
    template: tv
    priority: 2
  sort_tv:
    priority: 2
    no_entries_ok: yes
    parsing:
      series: guessit
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    thetvdb_lookup: yes
    require_field: series_name
    all_series:
      parse_only: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          if mediainfo "{{ location }}" | grep EAC3; then
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && ffmpeg -hwaccel auto -y -i "{{ location }}" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          else
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && cp "{{ location }}" "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          fi
  sort_movies:
    priority: 2
    no_entries_ok: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    require_field: movie_name
    imdb_lookup: yes
    exec:
      auto_escape: yes
      on_output:
       for_entries: |
         if mediainfo "{{ location }}" | grep EAC3; then
           mkdir -p "/storage/movies/{{ movie_name }} ({{ movie_year }})" && ffmpeg -hwaccel auto -y -i "{{ location }}" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "/storage/movies/{{ movie_name }} ({{ movie_year }})/{{ movie_name }} ({{ movie_year }}){{ location | pathext }}"
         else
           mkdir -p "/storage/movies/{{ movie_name }} ({{ movie_year }})" && cp "{{ location }}" "/storage/movies/{{ movie_name }} ({{ movie_year }})/{{ movie_name }} ({{ movie_year }}){{ location | pathext }}"
         fi
  remove_stale_torrents:
    from_transmission:
      host: transmission
      port: 9091
      username: keviinplz
      password: # owo
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok: reject
      - not transmission_idle_limit_ok: reject
    transmission:
      host: transmission
      port: 9091
      username: keviinplz
      password: # owo
      action: purge
```

Finalmente, mi repositorio de trabajo tiene la siguiente estructura

```bash
├── config
├── docker-compose.yaml
├── downloads
│   ├── complete
│   ├── incomplete
│   └── uncomplete
├── flexget
│   ├── Dockerfile
│   ├── config.yml
│   ├── files
│   │   └── scripts
│   │       └── init.sh
├── media
│   ├── movies
│   └── series
└── transmission
    ├── config
    │   └── sysctl.conf
    ├── settings.json
```
