### ISSUE TITLE
Plex dice que los directorios estan vacios 

### ISSUE THREAD

**Issue by Rubiooo04** [pablokbs/plex-rpi#31]
**Version de docker y del contenedor**
docker-compose con la versión _1.25.0_ y la versión del contenedor es _plex:1.30.0.6486-armhf_

**Docker-Compose.yml**

```
  plex:
    image: jaymoulin/plex:1.30.0.6486-armhf
    expose:
      - 32400
      - 33400
    hostname: raspberry
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
```
**.ENV**

```
MEDIA=/media/hdd/media
STORAGE=/media/hdd/
```

**Descripción breve**
Cuando intento configurar el directorio de plex donde deberían de estar las pelis o series me sale vacío y no me aparece ninguna carpeta

**Pasos que he seguido**
1. docker-compose up -d
2. http://my_machine_ip:32400/manage
3. Darle en agregar biblioteca; seleccionar _PELICULAS_ ; Clickar en la izquierda donde pone _AÑADIR CARPETA_ y darle a _Ver carpeta de medios_

**Que me esperaba que pasase**
Cuando le de a la _/_ de los directorio y luego al directorio de _media_ deberia aparecer una carpeta que se llame hdd ( no aparece ) y dentro de esa carpeta ahi estan los archivos de _Plex Media Sever_ y 2 carpetas de _pelis_ y _series_ sin embargo no me aparece ninguna de estas carpetas

<img width="960" alt="Plex" src="https://user-images.githubusercontent.com/77902247/209725212-5c97a9e0-d3ac-46d7-89d1-ff299ff4bcae.png">
