### ISSUE TITLE
Problema con flexget y transmission 

### ISSUE THREAD

**Issue by Nashrc** [pablokbs/plex-rpi#44]
hola que buenas!!

que tengo mal que no me funciona habro las apps o sea flexget y tambien transmission por medio del edge pero no se actualizan con los rss transmission funciona porque manual puedo poner cosas pero flexget no entiendo nada...

```

version: "3"
services:
  flexget:
    image: wiserain/flexget
    container_name: flexget  # Asegúrate de usar un nombre válido aquí
    restart: on-failure:5
    ports:
      - 5050:5050
    volumes:
      - /home/docker/apps/flexget/to/config:/config
      - /home/docker/apps/flexget/to/custom-cont-init.d:/custom-cont-init.d
      - /home/docker/apps/transmission/to/downloads:/downloads
      - /home/media:/storage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina  # Reemplaza esto con tu zona horaria
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=**********
```

```
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=admin
      - PASS=password1234
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /home/docker/apps/transmission/to/data:/config
      - /home/docker/apps/transmission/to/downloads:/downloads
      - /home/docker/apps/transmission/to/watch/folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```

```
web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 30

tasks:
  my_task:
    rss: https://eztv.ag/ezrss.xml
    series:
      - Coops

    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "**********"
```
desde ya muchas gracias
