### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by xejarque** [pablokbs/plex-rpi#6]
Hola Pablo, me acabo de dar cuenta que el contenido del Readme.md no se corresponde con el docker-compose.yml, en el readme usas tu repo de rutorrent mientras que el docker-compose usas linuxserver/rutorrent.

**Comment by pablokbs** [comment]
Si, eso es porq la versión nueva tiene un par de arreglos que la mía no
tenía, hacete un PR y lo mergeamos!

**Comment by joseforte** [comment]
Me sumo al pedido de modificacion por la discrepancia entre el README y el docker-compose.yml
Tambien queria aportar que hay una nueva imagen de rutorrent y de plex que habria que correrlas de esta forma
```
rtorrent:
    image: linuxserver/rutorrent:arm32v7-latest
    environment:
      - PUID=1000
      - PGID=1000

```

```
plex:
    image: jaymoulin/plex:1.16.3-armhf
    ports:
      - 32400:32400
      - 33400:33400
    volumes:
      - /media/pi/RasPI/plex:/root/Library
      - /media/pi/RasPI/media:/media
    restart: always
    network_mode: "host"
```
